apiVersion: v1
kind: Namespace
metadata:
  name: {{ required "name is required!" .Values.google.namespace }}
  annotations:
    cnrm.cloud.google.com/project-id: "{{ required "projectId is required!" .Values.google.projectId }}"